### ISSUE TITLE
该项目疑似失效

### ISSUE THREAD

**Issue by PencilNavigator** [SunYufei/freenom#7]
该项目Action报错，于近日出现。本人Fork修改版也出现了同样报错。

> 
[1](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:1)
Run python3 run.py -u '***' -p '***'
[4](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:5)
Traceback (most recent call last):
[5](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:6)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
[6](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:7)
    conn = connection.create_connection(
[7](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:8)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
[8](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:9)
    raise err
[9](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:10)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
[10](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:11)
    sock.connect(sa)
[11](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:12)
TimeoutError: [Errno 110] Connection timed out
[12](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:13)

[13](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:14)
During handling of the above exception, another exception occurred:
[14](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:15)

[15](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:16)
Traceback (most recent call last):
[16](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:17)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
[17](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:18)
    httplib_response = self._make_request(
[18](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:19)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
[19](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:20)
    self._validate_conn(conn)
[20](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:21)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
[21](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:22)
    conn.connect()
[22](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:23)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
[23](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:24)
    conn = self._new_conn()
[24](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:25)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
[25](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:26)
    raise NewConnectionError(
[26](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:27)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f89c6fb36a0>: Failed to establish a new connection: [Errno 110] Connection timed out
[27](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:28)

[28](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:29)
During handling of the above exception, another exception occurred:
[29](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:30)

[30](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:31)
Traceback (most recent call last):
[31](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:32)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
[32](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:33)
    resp = conn.urlopen(
[33](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:34)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
[34](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:35)
    retries = retries.increment(
[35](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:36)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
[36](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:37)
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
[37](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:38)
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='my.freenom.com', port=443): Max retries exceeded with url: /dologin.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f89c6fb36a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[38](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:39)

[39](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:40)
During handling of the above exception, another exception occurred:
[40](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:41)

[41](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:42)
Traceback (most recent call last):
[42](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:43)
  File "run.py", line 15, in <module>
[43](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:44)
    instance.renew()
[44](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:45)
  File "/home/runner/work/freenom/freenom/freenom.py", line 46, in renew
[45](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:46)
    ok = self._login()
[46](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:47)
  File "/home/runner/work/freenom/freenom/freenom.py", line 41, in _login
[47](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:48)
    r = self._s.post(LOGIN_URL, data={'username': self._u, 'password': self._p})
[48](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:49)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
[49](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:50)
    return self.request('POST', url, data=data, json=json, **kwargs)
[50](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:51)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
[51](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:52)
    resp = self.send(prep, **send_kwargs)
[52](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:53)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
[53](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:54)
    r = adapter.send(request, **kwargs)
[54](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:55)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
[55](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:56)
    raise ConnectionError(e, request=request)
[56](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:57)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='my.freenom.com', port=443): Max retries exceeded with url: /dologin.php (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f89c6fb36a0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
[57](https://github.com/SunYufei/freenom/runs/7512429626?check_suite_focus=true#step:3:58)
Error: Process completed with exit code 1.

**Comment by SunYufei** [comment]
最近也发现出问题了，初步判断是网络不通，正在开发新的自动续期方法

**Comment by guest997** [comment]
> 最近也发现出问题了，初步判断是网络不通，正在开发新的自动续期方法

貌似封ip了。

**Comment by SunYufei** [comment]
> > 最近也发现出问题了，初步判断是网络不通，正在开发新的自动续期方法
> 
> 貌似封ip了。还有就是使用cf，发送请求都是404的。

workers 版本正在测试，会尽快解决出现的问题
